version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions"
    labels:
      - "dependencies"

  # Maintain pip dependencies while running Github Actions
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "pip github-actions"
      include: "scope"
    labels:
      - "dependencies"

  # Maintain dependencies for Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "poetry"
      include: "scope"
    labels:
      - "dependencies"
