[tool.poetry]
name = "github-release-fetcher"
version = "0.1.0"
description = "Tool to fetch releases from Github"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pziggo/github-release-fetcher"
repository = "https://github.com/pziggo/github-release-fetcher"
keywords = ["github"]
authors = ["Patrick Ziegler <ziggo@zaebos.de>"]

[tool.poetry.dependencies]
python = "^3.6.1"
click = "^7.1.2"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.11.1"
flake8-import-order = "^0.18.1"
safety = "^1.10.3"
mypy = "^0.812"
flake8-annotations = "^2.6.1"
typeguard = "^2.11.1"
flake8-docstrings = "^1.5.0"
darglint = "^1.7.0"
xdoctest = "^0.15.4"
pep8-naming = "^0.11.1"

[tool.poetry.scripts]
github-release-fetcher = "github_release_fetcher.console:main"

[tool.coverage.paths]
source = ["src", "*./site-packages"]

[tool.coverage.run]
branch = true
source = ["github_release_fetcher"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
