name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install --constraint=.github/workflows/constraints.txt nox
    - run: pip install --constraint=.github/workflows/constraints.txt poetry
    - run: nox --sessions tests-3.9 coverage
    - run: bash <(curl -s https://codecov.io/bash)