name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        include:
          - { python-version: 3.9, os: ubuntu-latest }
          - { python-version: 3.9, os: macos-latest }
          - { python-version: 3.8, os: ubuntu-latest }
          - { python-version: 3.7, os: ubuntu-latest }
          - { python-version: 3.6, os: ubuntu-latest }
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2.3.2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install --constraint=.github/workflows/constraints.txt nox
    - run: pip install --constraint=.github/workflows/constraints.txt poetry
    - run: nox